---
swagger: "2.0"
info:
  description: "With GitHub Sync + YAML (Resolved). This produces an extra field, responsesObject.\nThere must be a $ref pointing to a remote domain, for a response.\nNote this is OAS 2.0.\n"
  version: 1.0.0
  title: Responses Object
paths:
  /foo:
    get:
      parameters: []
      responses:
        "400":
          description: General Error
