/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValidationErrors struct {

	// The line number where the issue occurs. 0-indexed. If for some reason, the broken rule does not include a line number, default to zero. 
	Line int32 `json:"line"`

	// The issue's description, human friendly. Pertaining to how the user can fix it.
	Description string `json:"description"`

	Severity string `json:"severity,omitempty"`
}
