/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiMetadata struct {

	DefaultVersion string `json:"defaultVersion,omitempty"`

	Categories []string `json:"categories"`

	Tags []string `json:"tags"`

	Links []ApiMetadataLink `json:"links,omitempty"`
}
