/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration details required to create an SCM configuration. additionalProperties is being used to allow for flexibiliy when adding fields to a SCM integration.
type ScmIntegrationPluginConfiguration struct {

	ConfigType string `json:"configType"`

	Name string `json:"name,omitempty"`

	Token string `json:"token,omitempty"`

	Branch string `json:"branch,omitempty"`

	Owner string `json:"owner,omitempty"`

	Repository string `json:"repository,omitempty"`

	OutputFile string `json:"outputFile,omitempty"`

	Target string `json:"target,omitempty"`

	SyncMethod string `json:"syncMethod,omitempty"`

	Enabled bool `json:"enabled,omitempty"`

	OutputFolder string `json:"outputFolder,omitempty"`

	ProvidedPaths []string `json:"providedPaths,omitempty"`

	IgnoredPaths []string `json:"ignoredPaths,omitempty"`

	ManagedPaths []string `json:"managedPaths,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Project string `json:"project,omitempty"`

	ProjectCollection string `json:"projectCollection,omitempty"`

	PersonalAccessToken string `json:"personalAccessToken,omitempty"`

	Account string `json:"account,omitempty"`

	Url string `json:"url,omitempty"`

	Host string `json:"host,omitempty"`
}
