/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CommentsBatch struct {

	AddComment []NewComment `json:"addComment,omitempty"`

	UpdateComment map[string]ClosableCommentPatch `json:"updateComment,omitempty"`

	UpdateStatus map[string]string `json:"updateStatus,omitempty"`

	DeleteComment []string `json:"deleteComment,omitempty"`

	AddReply map[string][]NewReply `json:"addReply,omitempty"`

	UpdateReply map[string]map[string]CommentPatch `json:"updateReply,omitempty"`

	DeleteReply map[string][]string `json:"deleteReply,omitempty"`
}
