/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntryId struct {

	Owner string `json:"owner,omitempty"`

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`
}
