/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DraftModel struct {

	Yaml string `json:"yaml,omitempty"`

	Comments []ClosableComment `json:"comments,omitempty"`
}
