/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration details used to create a Webhook integration.
type WebhookIntegration struct {

	// ID of the integration
	Id string `json:"id,omitempty"`

	// The display name of the integration. Must be unique among all integrations configured for the given API version.
	Name string `json:"name"`

	// Whether the integration is enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`

	// Integration type.
	ConfigType string `json:"configType"`

	// URL to send notification.
	Url string `json:"url"`

	// Content type of notification.
	ContentType string `json:"contentType"`

	// Lifecycle events that will trigger webhook.
	LifecycleEvents []string `json:"lifecycleEvents,omitempty"`

	// Custom HTTP headers to be sent with webhook notifications. Use the format \"name: value\" for each header.
	AdditionalHeaders []string `json:"additionalHeaders,omitempty"`
}
