/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Comment struct {

	Id string `json:"id"`

	User *User `json:"user"`

	Created time.Time `json:"created,omitempty"`

	Modified time.Time `json:"modified,omitempty"`

	Body string `json:"body"`
}
