/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NotCollaboratorProjectMembers struct {

	MissingApisMembers []MissingSpecMembers `json:"missingApisMembers,omitempty"`

	MissingDomainsMembers []MissingSpecMembers `json:"missingDomainsMembers,omitempty"`

	MissingApisTeams []MissingSpecMembers `json:"missingApisTeams,omitempty"`

	MissingDomainsTeams []MissingSpecMembers `json:"missingDomainsTeams,omitempty"`
}
