/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration details used to create an API Auto Mocking integration.
type AutoMockingIntegration struct {

	// ID of the integration
	Id string `json:"id,omitempty"`

	// The display name of the integration. Must be unique among all integrations configured for the given API version.
	Name string `json:"name"`

	// Whether the integration is enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`

	// Integration type.
	ConfigType string `json:"configType"`

	// Response content type that the mock server will return if no `Accept` header is specified.
	DefaultResponseType string `json:"defaultResponseType,omitempty"`

	// Bearer token that users will need to send in requests to the mock server (private APIs only).
	Token string `json:"token,omitempty"`

	// Whether to update the `host`/`servers` in the API definition to point to the mock server.
	Modify bool `json:"modify,omitempty"`
}
