/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ForkVersion struct {

	Owner string `json:"owner"`

	Name string `json:"name"`

	Version string `json:"version"`

	Project string `json:"project,omitempty"`

	// Whether the forked version should be public (`false`) or private (`true`). If the value is not set, then the original version's setting will be used.
	Private bool `json:"private,omitempty"`
}
