/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MissingSpecMembers struct {

	Spec *SimpleSpec `json:"spec,omitempty"`

	Names []string `json:"names,omitempty"`
}
