/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Can be used as the parent superclass for any plugin integrations which are available for usage as part of SwaggerHub.
type IntegrationPluginConfiguration struct {

	ConfigType string `json:"configType"`
}
