/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Configuration details used to create a GitLab integration
type GitLabIntegration struct {

	// ID of the integration
	Id string `json:"id,omitempty"`

	// The display name of the integration. Must be unique among all integrations configured for the given API version.
	Name string `json:"name"`

	// Whether the integration is enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`

	// The branch to synchronize to. If it does not exist in the repository, it will be created based on the default branch. Branch must not contain whitespace characters. 
	Branch string `json:"branch,omitempty"`

	// The repository to synchronize with.
	Repository string `json:"repository,omitempty"`

	// The type of code to generate and push to the repository. For the possible values, start creating an SCM integration manually and check the \"Generated API Code\" values. Note that the available codegens for OAS2 and OAS3 vary. 
	Target string `json:"target,omitempty"`

	// \"Basic Sync\" or \"Advanced Sync\". Basic Sync will manage all files and folders in the branch. Advanced Sync allows you to define which files and folders will be managed by SwaggerHub. 
	SyncMethod string `json:"syncMethod,omitempty"`

	// The output folder for the generated code or definition. This location is relative to the repository root. If this folder does not exist, it will be created. 
	OutputFolder string `json:"outputFolder,omitempty"`

	// If target is the YAML/JSON, this is the file name for the generated definition.
	OutputFile string `json:"outputFile,omitempty"`

	// Partially Managed Paths Files in these locations will be created only if they do not exist. Existing files will not be modified. 
	ProvidedPaths []string `json:"providedPaths,omitempty"`

	// Ignored Paths Paths to ignore from code generation, relative to the Output Folder 
	IgnoredPaths []string `json:"ignoredPaths,omitempty"`

	// Fully Managed Paths Files in these locations will be fully managed by SwaggerHub relative to the Output Folder. All files will be overwritten and existing files may be deleted if not needed. 
	ManagedPaths []string `json:"managedPaths,omitempty"`

	// Integration type to create.
	ConfigType string `json:"configType,omitempty"`

	// The GitLab host to connect to.
	Host string `json:"host,omitempty"`

	// A personal access token for accessing the target repository. Be sure to include read-write access to your repositories. 
	PersonalAccessToken string `json:"personalAccessToken,omitempty"`

	// The owner of the repository to synchronize with.
	Owner string `json:"owner,omitempty"`
}
