/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Page struct {

	Offset int32 `json:"offset,omitempty"`

	Total int64 `json:"total,omitempty"`

	Items []interface{} `json:"items,omitempty"`
}
