/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Project struct {

	// Organization in which the project exists
	Owner string `json:"owner,omitempty"`

	// Project name
	Name string `json:"name,omitempty"`

	// Project description
	Description string `json:"description,omitempty"`

	// A list of APIs included in this project. The APIs must belong to the same organization as the project. API names are case-sensitive. 
	Apis []string `json:"apis,omitempty"`

	// A list of domains included in this project. The domains must belong to the same organization as the project. Domain names are case-sensitive. 
	Domains []string `json:"domains,omitempty"`
}
