/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PluginConfiguration struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	ObjectId string `json:"objectId"`

	Lifecycles []string `json:"lifecycles"`

	Configuration *interface{} `json:"configuration,omitempty"`

	OwnerName string `json:"ownerName"`

	Path string `json:"path"`

	DefinitionId string `json:"definitionId"`

	Draft bool `json:"draft,omitempty"`
}
