/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrgStyleValidationRule struct {

	Type_ string `json:"type,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Value string `json:"value,omitempty"`

	Checked bool `json:"checked,omitempty"`

	Severity string `json:"severity,omitempty"`

	OasVersions []string `json:"oasVersions,omitempty"`

	Options []string `json:"options,omitempty"`
}
