/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Contains an orgs style validation stauts
type OrgStyleValidationEnabled struct {

	OrgName string `json:"orgName,omitempty"`

	Enabled bool `json:"enabled,omitempty"`
}
