/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NewVersion struct {

	// The name of the new version.
	Version string `json:"version"`

	// Whether the new version should be public or private.
	Private bool `json:"private,omitempty"`
}
