/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// a part of the API that was (or wasn't) changed
type ComparisonPart struct {

	// the type of change that this part describes * UNMODIFIED - this part is the same in both APIs. Only available for FULL compare. * INSERTED - this is present in `other` but missing in `base`. `base` will not be present. * DELETED - this is present in `base` but missing in `other`. `other` will not be present. * CHANGED - this has been changed between `base` and `other`. Both `base` and `other` present. 
	Type_ string `json:"type"`

	Base *ComparisonDetail `json:"base,omitempty"`

	Other *ComparisonDetail `json:"other,omitempty"`
}
