/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// a recent user asset from any supported product displayed on the portal front page and in the gear menu together with a deep link back to the product
type UserAsset struct {

	// a user-friendly name of this asset
	Name string `json:"name"`

	// a type identifier for this asset in the format product/type
	Type_ string `json:"type"`

	// a deep link that will open the corresponding asset in its product
	Link string `json:"link"`

	// a uri that can be used by the target of a cross-product action to retrieve the asset with a GET request
	Uri string `json:"uri,omitempty"`

	// an identifier for the product this asset belongs to (for filtering, etc)
	Product string `json:"product"`

	// when this asset was last updated
	Timestamp time.Time `json:"timestamp"`
}
