/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Common configuration details required to create an integration using the `POST /apis/{owner}/{api}/{version}/integrations` endpoint
type IntegrationConfiguration struct {

	// ID of the integration
	Id string `json:"id,omitempty"`

	// The display name of the integration. Must be unique among all integrations configured for the given API version.
	Name string `json:"name"`

	// Whether the integration is enabled or disabled.
	Enabled bool `json:"enabled,omitempty"`
}
