/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Collaboration struct {

	Owner string `json:"owner,omitempty"`

	Owners []string `json:"owners,omitempty"`

	Hint *CollaborationHint `json:"hint,omitempty"`

	Members []CollaborationMembership `json:"members,omitempty"`

	PendingMembers []CollaborationMembership `json:"pendingMembers,omitempty"`

	Teams []CollaborationTeamMembership `json:"teams,omitempty"`
}
