/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CodegenSettings struct {

	Server map[string]CodegenLanguage `json:"server,omitempty"`

	Client map[string]CodegenLanguage `json:"client,omitempty"`
}
