/*
 * SwaggerHub Registry API
 *
 * The registry API for SwaggerHub
 *
 * API version: 1.0.97
 * Contact: info@swaggerhub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApisJsonValueProperty struct {

	Type_ string `json:"type"`

	Url string `json:"url,omitempty"`

	Value string `json:"value,omitempty"`
}
