swagger: '2.0'
info:
  version: '1'
  title: One
  description: Just One
paths: 
  /josh:
    get:
      responses: 
        200:  
          description: bob
          schema:
            $ref: "https://dev-api.swaggerhub.com/domains/ponelat/should-have-no-typos/1#/responses/GeneralError"