/**
 * title
 * description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as querystring from "querystring";
import * as url from "url";

import * as isomorphicFetch from "isomorphic-fetch";
import * as assign from "core-js/library/fn/object/assign";

interface Dictionary<T> { [index: string]: T; }
export interface FetchAPI { (url: string, init?: any): Promise<any>; }

const BASE_PATH = "https://api.github.com".replace(/\/+$/, '');

export interface FetchArgs {
    url: string;
    options: any; 
}

export class BaseAPI {
    basePath: string;
    fetch: FetchAPI;

    constructor(fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) {
        this.basePath = basePath;
        this.fetch = fetch;
    }
}

export interface UserData {
    "login"?: string;
    "id"?: number;
    "url"?: string;
    "location"?: string;
    "name"?: string;
}



/**
 * GitHubApi - fetch parameter creator
 */
export const GitHubApiFetchParamCreactor = {
    /** 
     * Get user data
     * Get user data
     * @param username The username, we want the data from.
     */
    getUser(params: {  username: string; }): FetchArgs {
        // verify required parameter "username" is set
        if (params["username"] == null) {
            throw new Error("Missing required parameter username when calling getUser");
        }
        const baseUrl = `/users/{username}`
            .replace(`{${"username"}}`, `${ params.username }`);
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = { method: "GET" };

        let contentTypeHeader: Dictionary<string>;
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
}

/**
 * GitHubApi - functional programming interface
 */
export const GitHubApiFp = {
    /** 
     * Get user data
     * Get user data
     * @param username The username, we want the data from.
     */
    getUser(params: { username: string;  }): (fetch: FetchAPI, basePath?: string) => Promise<UserData> {
        const fetchArgs = GitHubApiFetchParamCreactor.getUser(params);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * GitHubApi - object-oriented interface
 */
export class GitHubApi extends BaseAPI {
    /** 
     * Get user data
     * Get user data
     * @param username The username, we want the data from.
     */
    getUser(params: {  username: string; }) {
        return GitHubApiFp.getUser(params)(this.fetch, this.basePath);
    }
};

/**
 * GitHubApi - factory interface
 */
export const GitHubApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /** 
         * Get user data
         * Get user data
         * @param username The username, we want the data from.
         */
        getUser(params: {  username: string; }) {
            return GitHubApiFp.getUser(params)(fetch, basePath);
        },
    }
};

