/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Event_header_item (
  domain: Option[String],
  entity: Option[String],
  eventType: Option[String],
  sourceDt: Option[DateTime],
  eventDt: Option[DateTime],
  sourceId: Option[String],
  eventId: Option[String],
  dispatchId: Option[String])
   extends ApiModel


