/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Event_body (
  personId: Option[String],
  studentName: Option[String],
  yearTerm: Option[String],
  curriculumId: Option[String],
  titleCode: Option[String],
  sectionNumber: Option[String],
  teachingArea: Option[String],
  catalogNumber: Option[String],
  creditHours: Option[String])
   extends ApiModel


