/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Webhook_item (
  identityId: String,
  identityName: String,
  endpoint: String,
  pushOption: String,
  securityOption: String,
  securityKey: Option[String],
  contentType: String)
   extends ApiModel


