/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Add a cow to our collection of animals
   * 
   * Expected answers:
   *   code 200 :  (Cow added)
   */
  def addCow(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://dev-virtserver.swaggerhub.com/acme/another-pet/base", "/cows", "application/json")
      .withSuccessResponse[Unit](200)
        /**
   * Just a cat
   * 
   * Expected answers:
   *   code 200 :  (Just a cat resopnse)
   */
  def catsGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://dev-virtserver.swaggerhub.com/acme/another-pet/base", "/cats", "application/json")
      .withSuccessResponse[Unit](200)
      

}

