/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ArchivesApi {

  /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def archivesOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/archives", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Events Retrieved)
   *   code 204 :  (No results found with search criteria)
   *   code 400 :  (Unknown parameter in search criteria)
   * 
   * @param eventDt Defines a date-time range for the search. The expected parameter should be of the format &#39;(start_dt, end_dt)&#39;. The dates should be standard ISO format expressed in zulu time. Maximum time span is one day.
   * @param domain Limits the list where the domain attribute matches the string expression.  The string may include wild characters (&#39;*&#39;).  Since domains contain an embedded dot (\&quot;.\&quot;), the period must be explicitly expressed in the search string.  For example, &#39;edu.byu&#39; will limit the search to a specific domain, &#39;edu.*&#39; will limit the search to all &#39;edu&#39; domains, and &#39;*.byu*&#39; will limit the search to any domain that starts with &#39;byu&#39; in the first part of the domain.
   * @param entity Limits the list where the entity attribute matches the string expression.  The string may include wild characters (&#39;*&#39;).
   * @param eventType 
   * @param pageStart Specifies how far to skip into a large set
   * @param pageSize Specifies how many items to return from a large set
   */
  def getArchives(eventDt: String, domain: Option[String] = None, entity: Option[String] = None, eventType: Option[String] = None, pageStart: Option[Int], pageSize: Option[Int]): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/archives", "application/json")
      .withQueryParam("domain", domain)
      .withQueryParam("entity", entity)
      .withQueryParam("event_dt", eventDt)
      .withQueryParam("event_type", eventType)
      .withQueryParam("page_start", pageStart)
      .withQueryParam("page_size", pageSize)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](204)
      .withErrorResponse[Unit](400)
      

}

