/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Domain_definition_create
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DomainsApi {

  /**
   * 
   * Expected answers:
   *   code 201 :  (Domain Added)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to add a domain)
   *   code 403 :  (Access denied - not authorized to add a domain)
   *   code 409 :  (Body of the request contains conflicting, malformed, or invalid data)
   * 
   * @param body Request Body
   */
  def createDomain(body: Domain_definition_create): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/domains", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](409)
        /**
   * 
   * Expected answers:
   *   code 204 :  (Domain successfully removed)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to delete a domain)
   *   code 403 :  (Access denied - not authorized to delete a domain)
   * 
   * @param domain domain
   */
  def deleteDomain(domain: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://localhost", "/domains/{domain}", "application/json")
      .withPathParam("domain", domain)
      .withSuccessResponse[Unit](204)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   * 
   * @param domain domain
   */
  def domainOptions(domain: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/domains/{domain}", "application/json")
      .withPathParam("domain", domain)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def domainsOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/domains", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Domains Retrieved)
   *   code 204 :  (No results found)
   */
  def getDomains(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/domains", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](204)
      

}

