/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Entity_definition_item
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object EntitiesApi {

  /**
   * 
   * Expected answers:
   *   code 201 :  (Entity Added)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to add an entity)
   *   code 403 :  (Access denied - not authorized to add an entity)
   *   code 409 :  (Body of the request contains conflicting, malformed, or invalid data)
   * 
   * @param body Request Body
   */
  def createEntity(body: Entity_definition_item): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/entities", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](409)
        /**
   * 
   * Expected answers:
   *   code 204 :  (Entity successfully removed)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to delete an entity)
   *   code 403 :  (Access denied - not authorized to delete an entity)
   *   code 404 :  (Entity not found)
   * 
   * @param domain domain
   * @param entity entity
   */
  def deleteEntity(domain: String, entity: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://localhost", "/entities/{domain}/{entity}", "application/json")
      .withPathParam("domain", domain)
      .withPathParam("entity", entity)
      .withSuccessResponse[Unit](204)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](404)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def entitiesOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/entities", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   * 
   * @param domain domain
   * @param entity entity
   */
  def entityOptions(domain: String, entity: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/entities/{domain}/{entity}", "application/json")
      .withPathParam("domain", domain)
      .withPathParam("entity", entity)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (entities Retrieved)
   *   code 204 :  (No results found)
   * 
   * @param entity 
   */
  def getEntities(entity: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/entities", "application/json")
      .withQueryParam("entity", entity)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](204)
      

}

