/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Subscription_create
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object SubscriptionsApi {

  /**
   * 
   * Expected answers:
   *   code 201 :  (Subscription Added)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to add an entity)
   *   code 403 :  (Access denied - not authorized to add an entity)
   *   code 409 :  (Body of the request contains conflicting, malformed, or invalid data)
   * 
   * @param body Request Body
   */
  def createSubscription(body: Subscription_create): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/subscriptions", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](409)
        /**
   * 
   * Expected answers:
   *   code 204 :  (Entity successfully removed)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to delete an subscription)
   *   code 403 :  (Access denied - not authorized to delete an subscription)
   *   code 404 :  (Entity not found)
   * 
   * @param domain domain
   * @param entity entity
   * @param eventType event_type
   */
  def deleteSubscription(domain: String, entity: String, eventType: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://localhost", "/subscriptions/{domain}/{entity}/{event_type}", "application/json")
      .withPathParam("domain", domain)
      .withPathParam("entity", entity)
      .withPathParam("event_type", eventType)
      .withSuccessResponse[Unit](204)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](404)
        /**
   * 
   * Expected answers:
   *   code 200 :  (subscriptions Retrieved)
   *   code 204 :  (No results found)
   * 
   * @param ecaIdentityId 
   * @param domain 
   * @param entity 
   * @param eventType 
   */
  def getSubscriptions(ecaIdentityId: String, domain: Option[String] = None, entity: Option[String] = None, eventType: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/subscriptions", "application/json")
      .withQueryParam("eca_identity_id", ecaIdentityId)
      .withQueryParam("domain", domain)
      .withQueryParam("entity", entity)
      .withQueryParam("event_type", eventType)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](204)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   * 
   * @param domain domain
   * @param entity entity
   * @param eventType event_type
   */
  def subscriptionOptions(domain: String, entity: String, eventType: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/subscriptions/{domain}/{entity}/{event_type}", "application/json")
      .withPathParam("domain", domain)
      .withPathParam("entity", entity)
      .withPathParam("event_type", eventType)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def subscriptionsOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/subscriptions", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      

}

