/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object SummariesApi {

  /**
   * 
   * Expected answers:
   *   code 200 :  (summaries Retrieved)
   *   code 204 :  (No results found)
   * 
   * @param domain 
   * @param entity 
   * @param eventDate 
   * @param eventType 
   * @param pageStart Specifies how far to skip into a large set
   * @param pageSize Specifies how many items to return from a large set
   */
  def getSummaries(domain: Option[String] = None, entity: Option[String] = None, eventDate: Option[String] = None, eventType: Option[String] = None, pageStart: Option[Int], pageSize: Option[Int]): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/summaries", "application/json")
      .withQueryParam("domain", domain)
      .withQueryParam("entity", entity)
      .withQueryParam("event_date", eventDate)
      .withQueryParam("event_type", eventType)
      .withQueryParam("page_start", pageStart)
      .withQueryParam("page_size", pageSize)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](204)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def summariesOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/summaries", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      

}

