/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Webhook_create
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object WebhooksApi {

  /**
   * 
   * Expected answers:
   *   code 204 :  (Webhook successfully removed)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to delete an subscription)
   *   code 403 :  (Access denied - not authorized to delete an subscription)
   *   code 404 :  (Webhook not found)
   */
  def deleteWebhook(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://localhost", "/webhooks", "application/json")
      .withSuccessResponse[Unit](204)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](404)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Collection Retrieved)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to access data)
   *   code 403 :  (Access denied to protected data)
   *   code 404 :  (No Cars satisfy the query parameters - the collection is empty)
   *   code 409 :  (Query parameters conflict or are malformed)
   * 
   * @param identityId 
   * @param identityName 
   * @param endpoint 
   * @param pushOption 
   */
  def getWebhooks(identityId: String, identityName: Option[String] = None, endpoint: Option[String] = None, pushOption: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://localhost", "/webhooks", "application/json")
      .withQueryParam("identity_id", identityId)
      .withQueryParam("identity_name", identityName)
      .withQueryParam("endpoint", endpoint)
      .withQueryParam("push_option", pushOption)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](404)
      .withErrorResponse[Unit](409)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Event Item Retrieved)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to access data)
   *   code 403 :  (Access denied to protected data)
   *   code 404 :  (Webhook not found)
   * 
   * @param body Request Body
   */
  def modifyWebhook(body: Webhook_create): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://localhost", "/webhooks", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](404)
        /**
   * 
   * Expected answers:
   *   code 201 :  (Event raised)
   *   code 400 :  (Invalid Request - unable to interpret request)
   *   code 401 :  (Authentication required to add a webhook)
   *   code 403 :  (Access denied - not authorized to add a webhook)
   *   code 409 :  (Body of the request contains conflicting, malformed, or invalid data)
   * 
   * @param body Request Body
   */
  def registerWebhook(body: Webhook_create): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/webhooks", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[Unit](409)
        /**
   * 
   * Expected answers:
   *   code 200 :  (Successful)
   *   code 400 :  (Invalid Request - unable to interpret request)
   */
  def webhooksOptions(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.OPTIONS, "https://localhost", "/webhooks", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
      

}

